[tool.poetry]
name = "cbdetect"
version = "0.1.0"
description = ""
authors = ["Tage Johansson <tajo9185@student.uu.se>"]
readme = "README.md"

[tool.poetry.scripts]
fens = "cbdetect.gen_diagrams:main"

[tool.poetry.dependencies]
python = "^3.12"
chess = "^1.10.0"
fen2img = {path = "fen2img"}
pillow = "^10.3.0"


[tool.poetry.group.dev.dependencies]
pyright = "^1.1.366"
ruff = "^0.4.8"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pyright]
exclude = ["fen2img/"]

[tool.ruff]
exclude = ["fen2img/"]
line-length = 100

[tool.ruff.format]
docstring-code-format = true
preview = true
skip-magic-trailing-comma = true

[tool.ruff.lint]
select = [
    "E",  # pycodestyle
    "F",  # pyflakes
    "UP",  # pyupgrade
    "B",  # flake8-bugbear
    "SIM",  # flake8-simplify
    "RUF",  # ruff
    "I",  # isort
]

[tool.ruff.lint.isort]
split-on-trailing-comma = false
